feat: update script to gotecq

diff --git a/mac b/mac
--- a/mac
+++ b/mac
@@ -1,216 +1,199 @@
-#!/bin/sh
+#!/bin/bash
 
-# Welcome to the thoughtbot laptop script!
-# Be prepared to turn your laptop (or desktop, no haters here)
-# into an awesome development machine.
+# Nimble Laptop Setup with Fish shell
+# This script will set up a development machine using Fish instead of Zsh
 
-# shellcheck disable=SC3043
+set -e
+trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
 
 fancy_echo() {
   local fmt="$1"; shift
-
-  # shellcheck disable=SC2059
-  printf "\\n$fmt\\n" "$@"
+  printf "\n$fmt\n" "$@"
 }
 
-append_to_zshrc() {
-  local text="$1" zshrc
-  local skip_new_line="${2:-0}"
+pre_setup() {
+  mkdir -p "$HOME/.config/fish"
 
-  if [ -w "$HOME/.zshrc.local" ]; then
-    zshrc="$HOME/.zshrc.local"
-  else
-    zshrc="$HOME/.zshrc"
+  if [ ! -f "$HOME/.Brewfile" ]; then
+    touch "$HOME/.Brewfile"
   fi
 
-  if ! grep -Fqs "$text" "$zshrc"; then
-    if [ "$skip_new_line" -eq 1 ]; then
-      printf "%s\\n" "$text" >> "$zshrc"
-    else
-      printf "\\n%s\\n" "$text" >> "$zshrc"
+  ARCH="$(uname -m)"
+  if [ "$ARCH" = "arm64" ]; then
+    HOMEBREW_PREFIX="/opt/homebrew"
+  else
+    HOMEBREW_PREFIX="/usr/local"
+  fi
+}
+
+append_to_fish() {
+  local text="$1"
+  local fish_config="$HOME/.config/fish/config.fish"
+
+  touch "$fish_config"
+
+  if ! grep -Fqs "$text" "$fish_config"; then
+    echo "$text" >> "$fish_config"
+  fi
+}
+
+config_fish() {
+  read -r -p "Do you want to configure Fish shell? [Y|n] " response
+  if [[ ! $response =~ (n|no|N) ]]; then
+    fancy_echo "Installing Fish shell"
+    brew install fish
+
+    fancy_echo "Setting Fish as default shell"
+    if ! grep -q "$(which fish)" /etc/shells; then
+      echo "$(which fish)" | sudo tee -a /etc/shells
     fi
+    chsh -s "$(which fish)"
+
+    append_to_fish "eval (/opt/homebrew/bin/brew shellenv)"
+
+    # --- Fisher setup ---
+    fancy_echo "Installing fisher (Fish plugin manager)"
+    fish -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher'
+
+
+    # --- Install useful plugins ---
+    fish -c 'fisher install \
+      jorgebucaran/autopair.fish \
+      patrickf1/fzf.fish \
+      jhillyerd/plugin-git \
+      budimanjojo/tmux.fish \
+      blackjid/plugin-kubectl \
+      barnybug/docker-fish-completion'
+
+    fancy_echo "Configured Fish with fisher + plugins"
   fi
 }
 
-# shellcheck disable=SC2154
-trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
-
-set -e
-
-if [ ! -d "$HOME/.bin/" ]; then
-  mkdir "$HOME/.bin"
-fi
-
-if [ ! -f "$HOME/.zshrc" ]; then
-  touch "$HOME/.zshrc"
-fi
-
-# shellcheck disable=SC2016
-append_to_zshrc 'export PATH="$HOME/.bin:$PATH"'
-
-# Determine Homebrew prefix
-arch="$(uname -m)"
-if [ "$arch" = "arm64" ]; then
-  HOMEBREW_PREFIX="/opt/homebrew"
-else
-  HOMEBREW_PREFIX="/usr/local"
-fi
-
-update_shell() {
-  local shell_path;
-  shell_path="$(command -v zsh)"
-
-  fancy_echo "Changing your shell to zsh ..."
-  if ! grep "$shell_path" /etc/shells > /dev/null 2>&1 ; then
-    fancy_echo "Adding '$shell_path' to /etc/shells"
-    sudo sh -c "echo $shell_path >> /etc/shells"
-  fi
-  sudo chsh -s "$shell_path" "$USER"
+install_tsrc() {
+    pipx install tsrc
 }
 
-case "$SHELL" in
-  */zsh)
-    if [ "$(command -v zsh)" != "$HOMEBREW_PREFIX/bin/zsh" ] ; then
-      update_shell
-    fi
-    ;;
-  *)
-    update_shell
-    ;;
-esac
 
-# checks architecture
-if [ "$(uname -m)" = "arm64" ]
-  then
-  # checks if Rosetta is already installed
-  if ! pkgutil --pkg-info=com.apple.pkg.RosettaUpdateAuto > /dev/null 2>&1
-  then
-    echo "Installing Rosetta"
-    # Installs Rosetta2
-    softwareupdate --install-rosetta --agree-to-license
-  else
-    echo "Rosetta is installed"
-  fi
-fi
-
-
-gem_install_or_update() {
-  if gem list "$1" --installed > /dev/null; then
-    gem update "$@"
-  else
-    gem install "$@"
-  fi
-}
-
-if ! command -v brew >/dev/null; then
-  fancy_echo "Installing Homebrew ..."
+install_homebrew() {
+  if ! command -v brew >/dev/null; then
+    fancy_echo "Installing Homebrew ..."
     /bin/bash -c \
       "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-
-    append_to_zshrc "eval \"\$($HOMEBREW_PREFIX/bin/brew shellenv)\""
-
     export PATH="$HOMEBREW_PREFIX/bin:$PATH"
-fi
+  fi
+}
 
-if brew list | grep -Fq brew-cask; then
-  fancy_echo "Uninstalling old Homebrew-Cask ..."
-  brew uninstall --force brew-cask
-fi
+append_general_dependencies() {
+  fancy_echo "Appending general dependencies to Brewfile"
 
-fancy_echo "Updating Homebrew formulae ..."
-brew update --force # https://github.com/Homebrew/brew/issues/1151
-brew bundle --file=- <<EOF
-tap "thoughtbot/formulae"
-tap "heroku/brew"
+  tee "$HOME/.Brewfile" <<-EOF
+    # Tools
+    brew "git"
 
-# Unix
-brew "universal-ctags"
-brew "fzf"
-brew "git"
-brew "openssl"
-brew "rcm"
-brew "reattach-to-user-namespace"
-brew "the_silver_searcher"
-brew "tmux"
-brew "vim"
-brew "watchman"
-brew "zsh"
+    # Editors
+    cask "visual-studio-code" unless File.directory?("/Applications/Visual Studio Code.app")
 
-# Heroku
-brew "heroku/brew/heroku"
-brew "parity"
-
-# GitHub
-brew "gh"
-
-# Image manipulation
-brew "imagemagick"
-
-# PDF Rendering
-brew "poppler"
-
-# Programming language prerequisites and package managers
-brew "libyaml" # should come after openssl
-brew "coreutils"
-brew "yarn"
-cask "gpg-suite-no-mail"
-
-# Databases
-brew "postgresql@14", restart_service: :changed
-brew "redis", restart_service: :changed
+    # Apps
+    cask "slack" unless File.directory?("/Applications/Slack.app")
+    cask "google-chrome" unless File.directory?("/Applications/Google Chrome.app")
+    cask "iterm2" unless File.directory?("/Applications/iTerm.app")
+    cask "openkey" unless File.directory?("/Applications/OpenKey.app")
 EOF
+}
 
-fancy_echo "Update heroku binary ..."
-brew unlink heroku
-brew link --force heroku
 
-fancy_echo "Configuring asdf version manager ..."
-if [ ! -d "$HOME/.asdf" ]; then
-  brew install asdf
-  append_to_zshrc "source $(brew --prefix asdf)/libexec/asdf.sh" 1
-else
-  brew upgrade asdf
-fi
+append_backend_dependencies() {
+  fancy_echo "Appending general dependencies to Brewfile"
 
-alias install_asdf_plugin=add_or_update_asdf_plugin
-add_or_update_asdf_plugin() {
-  local name="$1"
-  local url="$2"
+  brew tap hashicorp/tap
 
-  if ! asdf plugin list | grep -Fq "$name"; then
-    asdf plugin add "$name" "$url"
-  else
-    asdf plugin update "$name"
+  tee -a "$HOME/.Brewfile" <<-EOF
+    # Shell
+    brew "fish"
+
+    # Tools
+    brew "openssl"
+    brew "tmux"
+    brew "pyenv"
+    brew "pyenv-virtualenv"
+    brew "pipx"
+    brew "fzf"
+    brew "awscli"
+    brew "hashicorp/tap/terraform"
+
+    # Editors
+    brew "neovim"
+    cask "docker" unless File.directory?("/Applications/Docker.app")
+    cask "visual-studio-code" unless File.directory?("/Applications/Visual Studio Code.app")
+    cask "tableplus" unless File.directory?("/Applications/TablePlus.app")
+    cask "dbeaver-community" unless File.directory?("/Applications/DBeaver.app")
+
+    # Apps
+    cask "slack" unless File.directory?("/Applications/Slack.app")
+    cask "google-chrome" unless File.directory?("/Applications/Google Chrome.app")
+    cask "iterm2" unless File.directory?("/Applications/iTerm.app")
+EOF
+}
+
+append_mobile_dependencies() {
+  fancy_echo "Nothing to install for mobile at the moment"
+}
+
+append_frontend_dependencies() {
+  fancy_echo "Nothing to install for frontend at the moment"
+}
+
+install_dependencies() {
+  fancy_echo "Updating Homebrew formulae ..."
+  brew update --force
+
+  fancy_echo "Installing dependencies"
+  brew bundle --global --verbose --no-upgrade
+
+  fancy_echo "Installed dependencies"
+}
+
+install_laptop_local() {
+  if [ -f "$HOME/.laptop.local" ]; then
+    fancy_echo "Running your customizations from ~/.laptop.local ..."
+    . "$HOME/.laptop.local"
   fi
 }
 
-# shellcheck disable=SC1091
-. "$(brew --prefix asdf)/libexec/asdf.sh"
-add_or_update_asdf_plugin "ruby" "https://github.com/asdf-vm/asdf-ruby.git"
-add_or_update_asdf_plugin "nodejs" "https://github.com/asdf-vm/asdf-nodejs.git"
+install() {
+  read -r -p "Do you want to install Backend's dependencies? [y|N] " be_dep
+  read -r -p "Do you want to install Mobile's dependencies? [y|N] " mo_dep
+  read -r -p "Do you want to install Frontend's dependencies? [y|N] " fe_dep
 
-install_asdf_language() {
-  local language="$1"
-  local version
-  version="$(asdf list all "$language" | grep -v "[a-z]" | tr -s '\n' | tail -1)"
+  pre_setup
+  install_homebrew
+  append_general_dependencies
 
-  if ! asdf list "$language" | grep -Fq "$version"; then
-    asdf install "$language" "$version"
-    asdf set --home "$language" "$version"
+  if [[ $be_dep =~ (y|yes|Y) ]];then
+    append_backend_dependencies
   fi
+
+  if [[ $mo_dep =~ (y|yes|Y) ]];then
+    append_mobile_dependencies
+  fi
+
+  if [[ $fe_dep =~ (y|yes|Y) ]];then
+    append_frontend_dependencies
+  fi
+
+  install_dependencies
+
+  if [[ $be_dep =~ (y|yes|Y) ]];then
+    config_fish
+    install_tsrc
+  fi
+
+  install_laptop_local
+  brew cleanup
+  brew "pipx"
 }
 
-fancy_echo "Installing latest Ruby ..."
-install_asdf_language "ruby"
-gem update --system
-number_of_cores=$(sysctl -n hw.ncpu)
-bundle config --global jobs $((number_of_cores - 1))
+# Run
+install
 
-fancy_echo "Installing latest Node ..."
-install_asdf_language "nodejs"
-
-if [ -f "$HOME/.laptop.local" ]; then
-  fancy_echo "Running your customizations from ~/.laptop.local ..."
-  # shellcheck disable=SC1091
-  . "$HOME/.laptop.local"
-fi
+fancy_echo "Installation successful with Fish"
